// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP3f4JHAIQnFhSI-pi1HehtAdszk7-lkQ',
    appId: '1:958079297230:web:ac5866ec0087cb7b17129f',
    messagingSenderId: '958079297230',
    projectId: 'health2mama-e1e71',
    authDomain: 'health2mama-e1e71.firebaseapp.com',
    storageBucket: 'health2mama-e1e71.appspot.com',
    measurementId: 'G-PCLLR8NPPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP7clK-at3G_q0h2Xz88IK3Qka675oPKs',
    appId: '1:958079297230:android:35066efada25dcc317129f',
    messagingSenderId: '958079297230',
    projectId: 'health2mama-e1e71',
    storageBucket: 'health2mama-e1e71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi-Zcxp4F6lxSGftrTwiZniFklGp85R_k',
    appId: '1:958079297230:ios:b40febaf9c5bd4c217129f',
    messagingSenderId: '958079297230',
    projectId: 'health2mama-e1e71',
    storageBucket: 'health2mama-e1e71.appspot.com',
    androidClientId: '958079297230-8ikjgjb5kqkrbbs8tfb52s7vb29itut2.apps.googleusercontent.com',
    iosClientId: '958079297230-trfihg4cuknjcv7s7rishavjou2hdlq1.apps.googleusercontent.com',
    iosBundleId: 'com.heath2mama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi-Zcxp4F6lxSGftrTwiZniFklGp85R_k',
    appId: '1:958079297230:ios:b0c952a0566b2fdc17129f',
    messagingSenderId: '958079297230',
    projectId: 'health2mama-e1e71',
    storageBucket: 'health2mama-e1e71.appspot.com',
    androidClientId: '958079297230-8ikjgjb5kqkrbbs8tfb52s7vb29itut2.apps.googleusercontent.com',
    iosClientId: '958079297230-lb7ol0leabjaopjd2ie3hlsvsq28nmjv.apps.googleusercontent.com',
    iosBundleId: 'com.healthmama.health2mama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP3f4JHAIQnFhSI-pi1HehtAdszk7-lkQ',
    appId: '1:958079297230:web:fa58ad1d125f085c17129f',
    messagingSenderId: '958079297230',
    projectId: 'health2mama-e1e71',
    authDomain: 'health2mama-e1e71.firebaseapp.com',
    storageBucket: 'health2mama-e1e71.appspot.com',
    measurementId: 'G-TK6XV0HS5Y',
  );
}
